
name: OwnShop Staging Backend Deployment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install root dependencies
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend/
          include-hidden-files: true
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: backend

      - name: Deploy to Azure staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-myshop'
          slot-name: 'Production'
          package: backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE7D38DE4B764F5CAA4E1AD0FD3A2BDD }}
